[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"